/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import DAO.AbonnementDAO;
import Entite.Abonnement;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author abdou-jabar
 */
public class ModifierAbonnement extends javax.swing.JFrame {

    /**
     * Creates new form ModifierAbonnement
     */
    public ModifierAbonnement() {
        setUndecorated(true);
        initComponents();
        identifiantTextField.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) { verifier(); }
            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) { verifier(); }
            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) { verifier(); }
        });

        libelleTextField.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) { verifier(); }
            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) { verifier(); }
            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) { verifier(); }
        });

        prixTextField.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) { verifier(); }
            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) { verifier(); }
            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) { verifier(); }
        });
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        libelleTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        prixTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        modifierButton = new javax.swing.JButton();
        identifiantTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fermerButton = new javax.swing.JButton();
        annulerButton = new javax.swing.JButton();
        dureeField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MODIFIER L'ABONNEMENT");
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        libelleTextField.setText(Dashboard.libelle);
        libelleTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libelleTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Cantarell", 2, 15)); // NOI18N
        jLabel3.setText("Libelle");

        jLabel4.setFont(new java.awt.Font("Cantarell", 2, 15)); // NOI18N
        jLabel4.setText("Durée en mois");

        prixTextField.setText(String.valueOf(Dashboard.prix));
        prixTextField.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Cantarell", 2, 15)); // NOI18N
        jLabel5.setText("Prix mensuel");

        modifierButton.setFont(new java.awt.Font("Cantarell", 1, 17)); // NOI18N
        modifierButton.setText("MODIFIER");
        modifierButton.setEnabled(false);
        modifierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierButtonActionPerformed(evt);
            }
        });

        identifiantTextField.setEditable(false);
        identifiantTextField.setText(Dashboard.idAbonnement);

        jLabel2.setFont(new java.awt.Font("Cantarell", 2, 15)); // NOI18N
        jLabel2.setText("Identidiant");

        fermerButton.setFont(new java.awt.Font("Cantarell", 1, 17)); // NOI18N
        fermerButton.setText("FERMER");
        fermerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fermerButtonActionPerformed(evt);
            }
        });

        annulerButton.setFont(new java.awt.Font("Cantarell", 1, 17)); // NOI18N
        annulerButton.setText("ANNULER");
        annulerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerButtonActionPerformed(evt);
            }
        });

        dureeField.setText(Dashboard.dureeMois);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dureeField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(libelleTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(identifiantTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prixTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(modifierButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                .addComponent(annulerButton)
                                .addGap(21, 21, 21)
                                .addComponent(fermerButton)))
                        .addGap(15, 15, 15))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(identifiantTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(libelleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dureeField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prixTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modifierButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fermerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(annulerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void libelleTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libelleTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_libelleTextFieldActionPerformed

    private void modifierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierButtonActionPerformed
        Abonnement abonnement = new Abonnement();
        Dashboard dashboard = new Dashboard();
        
        abonnement.setId(identifiantTextField.getText());
        abonnement.setLibelle(libelleTextField.getText());
        abonnement.setDureeMois(Integer.parseInt(dureeField.getText()));
        float prixMensuel = Float.parseFloat(prixTextField.getText());
        abonnement.setPrixMensuel(prixMensuel);
        
        int reponse = JOptionPane.showConfirmDialog(rootPane, "Voulez vous vraiment modifier ?", "Confirmation", JOptionPane.YES_NO_OPTION);
        
        if (reponse == JOptionPane.YES_OPTION) {
            int resultat = AbonnementDAO.modifierAbonnement(abonnement);
        
            String succes = "Modification effectuée avec succès";
            String erreur = "Erreur de modification, ressayer";

            if(resultat > 0){
                JOptionPane.showMessageDialog(rootPane, succes);
                dashboard.chargerAbonnementsDansTable();
            }
            else{
                JOptionPane.showMessageDialog(rootPane, erreur);
            }
        }
    }//GEN-LAST:event_modifierButtonActionPerformed

    private void fermerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fermerButtonActionPerformed
        dispose();
    }//GEN-LAST:event_fermerButtonActionPerformed

    private void annulerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerButtonActionPerformed
        libelleTextField.setText("");
        dureeField.setText("");
        prixTextField.setText("");
    }//GEN-LAST:event_annulerButtonActionPerformed

    public void verifier(){
        if(!identifiantTextField.getText().trim().isEmpty() && !libelleTextField.getText().trim().isEmpty() && !prixTextField.getText().trim().isEmpty()){
            modifierButton.setEnabled(true);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifierAbonnement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifierAbonnement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifierAbonnement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifierAbonnement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        try {
            //</editor-fold>
            UIManager.setLookAndFeel(new FlatMacDarkLaf());
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(ModifierAbonnement.class.getName()).log(Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifierAbonnement().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annulerButton;
    private javax.swing.JTextField dureeField;
    private javax.swing.JButton fermerButton;
    private javax.swing.JTextField identifiantTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField libelleTextField;
    private javax.swing.JButton modifierButton;
    private javax.swing.JTextField prixTextField;
    // End of variables declaration//GEN-END:variables
}
